tools:
  - type: "function"
    function:
      name: "run_again"
      description: "Autonomously respond again to a specified channel. If using with other tools, this tool should ALWAYS be called last. this tool triggers Quest Boo to run again, and use more tools. Essential for chaining actions together."
      parameters:
        type: "object"
        properties:
          shouldRun:
            type: "boolean"
            description: "If true, the bot should produce another message"
          channelId:
            type: "string"
            description: "Discord channel ID where the next message should be sent"
        required:
          - shouldRun
          - channelId
        additionalProperties: false
  - type: "function"
    function:
      name: "remix_image"
      description: "Edit or remix an existing image shared in chat using Google Gemini AI. This tool allows you to take an image from the user's message and apply edits as requested by the user, like adding objects, changing the style, or modifying colors. This tool should be used when a user shares an image and asks for it to be edited."
      parameters:
        type: "object"
        properties:
          prompt:
            type: "string"
            description: "Description of how to edit the image (e.g., 'add a crown', 'make it cartoon style', 'turn it into anime')"
          channelId:
            type: "string"
            description: "Discord channel ID where the remixed image should be sent"
          imageUrl:
            type: "string"
            description: "URL of the image to remix. This should be extracted from the user's message or recent messages in the chat. It should be a LONG url starting with cdn.discordapp.com, but do NOT end at the file name. Include the full link that comes after or it will NOT work !"
        required:
          - prompt
          - channelId
          - imageUrl
        additionalProperties: false